Repository LikeLion-at-DGU/2025_DongBak_Frontend, pull requests merged in 2025-02, with the labels that each got.

#5 [Merge] #4 - 모바일 뷰 세팅 및 기초 세팅
  index.html
  package.json
  public/fonts/SUITE-Bold.ttf
  public/fonts/SUITE-ExtraBold.ttf
  public/fonts/SUITE-Heavy.ttf
  public/fonts/SUITE-Light.ttf
  public/fonts/SUITE-Medium.ttf
  public/fonts/SUITE-Regular.ttf
  public/fonts/SUITE-SemiBold.ttf
  public/images/.gitkeep
  public/vite.svg
  src/App.css
  src/App.jsx
  src/apis/.gitkeep
  src/assets/react.svg
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/index.css
  src/main.jsx
  src/pages/.gitkeep
  src/store/.gitkeep
  src/styles/global.js
  src/utils/.gitkeep
  yarn.lock
Labels: 🌏 Deploy, ⚙️ Setting, ☘️ 세호

#6 [Deploy] CD 테스트 진행
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  public/fonts/SUITE-Bold.ttf
  public/fonts/SUITE-ExtraBold.ttf
  public/fonts/SUITE-Heavy.ttf
  public/fonts/SUITE-Light.ttf
  public/fonts/SUITE-Medium.ttf
  public/fonts/SUITE-Regular.ttf
  public/fonts/SUITE-SemiBold.ttf
  public/images/.gitkeep
  src/App.jsx
  src/apis/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.jsx
  src/pages/.gitkeep
  src/store/.gitkeep
  src/styles/global.js
  src/utils/.gitkeep
  vite.config.js
  yarn.lock
Labels: 🌏 Deploy, ☘️ 세호

#18 [Feat] #17 - 에러페이지 ui 구현
  package.json
  public/images/MSITE_emoji.svg
  public/images/searchPage/Vector.svg
  public/images/searchPage/back.svg
  public/images/searchPage/search.svg
  src/apis/SearchService.js
  src/apis/instance.js
  src/components/SearchBox/SearchBox.jsx
  src/components/SearchBox/styled.js
  src/components/buttons/OneButton/OneButton.jsx
  src/components/buttons/OneButton/styled.js
  src/components/errorBox/ErrorBox.jsx
  src/components/errorBox/styled.js
  src/components/inputs/SearchInput/SearchInput.jsx
  src/components/inputs/SearchInput/styled.js
  src/constants/errorConstant.js
  src/constants/routeConstants.js
  src/constants/searchPageConstant.js
  src/hooks/useReloadPage.js
  src/hooks/useSearch.js
  src/pages/DeveloperPage/DeveloperPage.jsx
  src/pages/DeveloperPage/styled.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
  src/pages/notfound/NotFound.jsx
  src/pages/notfound/styled.js
  src/router.jsx
  yarn.lock
Labels: 🎨 Design, ☘️ 태준
