Repository LikeLion-at-DGU/2025_DongBak_Frontend, pull requests merged in 2025-03, with the labels that each got.

#20 [Feat] #13 - 검색 페이지 ui 구현
  package.json
  public/images/MSITE_emoji.svg
  public/images/searchPage/Vector.svg
  public/images/searchPage/back.svg
  public/images/searchPage/search.svg
  src/apis/SearchService.js
  src/apis/instance.js
  src/components/SearchBox/SearchBox.jsx
  src/components/SearchBox/styled.js
  src/components/buttons/OneButton/OneButton.jsx
  src/components/buttons/OneButton/styled.js
  src/components/errorBox/ErrorBox.jsx
  src/components/errorBox/styled.js
  src/components/inputs/SearchInput/SearchInput.jsx
  src/components/inputs/SearchInput/styled.js
  src/constants/errorConstant.js
  src/constants/routeConstants.js
  src/constants/searchPageConstant.js
  src/hooks/useReloadPage.js
  src/hooks/useSearch.js
  src/pages/DeveloperPage/DeveloperPage.jsx
  src/pages/DeveloperPage/styled.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
  src/pages/notfound/NotFound.jsx
  src/pages/notfound/styled.js
  src/router.jsx
  yarn.lock
Labels: ✨ Feature, 🎨 Design, ☘️ 태준

#24 [Merge] #8 - 공연 페이지 UI 구현
  jsconfig.json
  package.json
  public/images/.gitkeep
  public/images/arrow-down.svg
  public/images/arrow-up.svg
  public/images/divider-circle.svg
  src/components/Header/Header.jsx
  src/constants/navigateConstants.js
  src/constants/performaceData.js
  src/pages/Booth/BoothPage.jsx
  src/pages/performance/Performance.jsx
  src/pages/performance/_components/base/PerformancTime.jsx
  src/pages/performance/_components/base/PerformanceCard.jsx
  src/pages/performance/_components/container/PerformanceContainer.jsx
  src/pages/performance/_components/container/styled.js
  src/pages/performance/_components/header/PerformanceHeader.jsx
  src/pages/performance/_components/header/styled.js
  src/pages/performance/_components/timeTableItem/PerformanceTimeTableItem.jsx
  src/pages/performance/_components/timeTableItem/styled.js
  src/pages/performance/styled.js
  src/router.jsx
  src/stores/.gitkeep
  src/styles/global.js
  src/styles/theme.js
  vite.config.js
  yarn.lock
Labels: ✨ Feature, ☘️ 세호, 🎨 Design

#28 [Merge]#27 map UI modification 및 코드 리팩토링
  jsconfig.json
  package.json
  src/components/BoothDetailBox/BoothDetailBox.jsx
  src/components/BoothDetailBox/BoothInfo.jsx
  src/components/BoothList/BoothList.jsx
  src/components/BoothList/styled.js
  src/components/BoothMap/BoothMap.jsx
  src/components/BoothMap/styled.js
  src/components/Selector/CategorySelector.jsx
  src/components/Selector/DateSelector.jsx
  src/components/Selector/PlaceSelector.jsx
  src/components/Selector/styled.js
  src/constants/Booth/data.js
  src/hooks/Booth/useBoothDetail.js
  src/hooks/Booth/useBoothInfo.js
  src/hooks/Booth/useFoodDetail.js
  src/hooks/Booth/useFoodTruckInfo.js
  src/hooks/useBoothSelect.js
  src/pages/Booth/BoothDetailPage.jsx
  src/pages/Booth/BoothPage.jsx
  src/pages/Booth/FoodDetailPage.jsx
  vite.config.js
  yarn.lock
Labels: 🔨 Refactor, 🎨 Design, ☘️ 채민

#32 [Merge] #31 - 검색 페이지 API 연결
  .gitignore
  src/apis/SearchService.js
  src/apis/foodTruck.js
  src/apis/instance.js
  src/components/SearchBox/SearchBox.jsx
  src/components/errorBox/styled.js
  src/components/inputs/SearchInput/SearchInput.jsx
  src/hooks/useSearch.js
  src/pages/Booth/BoothPage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
  src/router.jsx
  vite.config.js
Labels: ✨ Feature, ☘️ 태준

#33 [Merge] #31 - 검색페이지 API 연결
  .gitignore
  src/apis/SearchService.js
  src/apis/foodTruck.js
  src/apis/instance.js
  src/components/SearchBox/SearchBox.jsx
  src/components/errorBox/styled.js
  src/components/inputs/SearchInput/SearchInput.jsx
  src/hooks/useSearch.js
  src/pages/Booth/BoothPage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
  src/router.jsx
  vite.config.js
Labels: ✨ Feature, ☘️ 태준

#35 [Merge] #30 - 공연페이지 디테일 수정
  jsconfig.json
  package.json
  public/_redirects
  public/images/clock1.svg
  public/images/now.svg
  public/images/record.svg
  public/images/user.svg
  src/apis/.gitkeep
  src/apis/instance.js
  src/apis/performance.js
  src/constants/common.js
  src/constants/performaceData.js
  src/hooks/.gitkeep
  src/hooks/useNowTime.js
  src/hooks/usePerformanceData.js
  src/pages/performance/Performance.jsx
  src/pages/performance/_components/base/PerformanceCard.jsx
  src/pages/performance/_components/container/styled.js
  src/pages/performance/_components/header/PerformanceHeader.jsx
  src/pages/performance/_components/timeTableItem/PerformanceTimeTableItem.jsx
  src/pages/performance/_components/timeTableItem/styled.js
  src/router.jsx
  src/styles/theme.js
  src/utils/.gitkeep
  src/utils/getCamelCaseValue.js
  src/utils/getInstagramId.js
  vite.config.js
  yarn.lock
Labels: ☘️ 세호, 🎨 Design

#40 [Merge] #25 - 공연페이지 에러 수정
  src/hooks/usePerformanceData.js
  src/pages/performance/Performance.jsx
  src/pages/performance/_components/base/PerformanceCard.jsx
  src/pages/performance/_components/timeTableItem/PerformanceTimeTableItem.jsx
  src/router.jsx
Labels: 🌏 Deploy, 🔨 Refactor, ☘️ 세호

#47 [Merge] #43 햄버거 메뉴 구현
  package.json
  public/images/hamburger.svg
  src/components/DeveloperCard/styled.js
  src/components/Header/Header.jsx
  src/components/Header/styled.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/styled.js
  src/constants/sidebarConstant.js
  src/pages/Booth/BoothPage.jsx
  src/styles/theme.js
  yarn.lock
Labels: ☘️ 태준

#52 [Merge]#36 booth search connection
  public/images/SearchBack.svg
  public/images/defaultImage.png
  public/images/map1.png
  public/images/map2.png
  public/images/pinkPin.png
  src/components/BoothDetailBox/BoothDetailBox.jsx
  src/components/BoothDetailBox/styled.js
  src/components/BoothList/BoothList.jsx
  src/components/BoothList/styled.js
  src/components/BoothMap/BoothMap.jsx
  src/components/ClubInfo/ClubInfo.jsx
  src/components/ClubInfo/RecruitInfo.jsx
  src/components/ClubInfo/styled.js
  src/components/ExpandableText/ExpandableText.jsx
  src/components/ExpandableText/styled.js
  src/components/Header/Header.jsx
  src/components/Header/styled.js
  src/hooks/useBoothSelect.js
  src/pages/Booth/BoothPage.jsx
  src/pages/Booth/styled.js
  src/pages/SearchPage/SearchPage.jsx
Labels: 🎨 Design, ☘️ 채민

#50 [Fix] 배포전 1차 QA 진행 및 오류 수정
  src/components/BoothDetailBox/BoothDetailBox.jsx
  src/components/Header/Header.jsx
  src/components/Header/styled.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/styled.js
  src/constants/developerpageConstants.js
  src/pages/Booth/BoothPage.jsx
  src/pages/DevelopersPage/DevelopersPage.jsx
  src/pages/DevelopersPage/styled.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
Labels: 🐞 Fix, ☘️ 태준

#53 [Merge] #48 - 긴급 UI 에러 수정
  src/components/Header/Header.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/styled.js
  src/pages/Booth/BoothPage.jsx
  src/pages/Booth/styled.js
  src/pages/performance/_components/header/styled.js
Labels: 🐞 Fix, ☘️ 세호

#60 [Merge] #51 - Footer 구현
  public/images/github.svg
  public/images/instaBlack.svg
  public/images/lion.svg
  src/components/Header/styled.js
  src/components/Sidebar/styled.js
  src/components/footer/Footer.jsx
  src/constants/common.js
  src/pages/Booth/BoothDetailPage.jsx
  src/pages/Booth/BoothPage.jsx
  src/pages/Booth/styled.js
  src/pages/DevelopersPage/DevelopersPage.jsx
  src/pages/DevelopersPage/styled.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/styled.js
  src/pages/notFound/NotFound.jsx
  src/pages/performance/Performance.jsx
  src/styles/theme.js
Labels: ✨ Feature, ☘️ 세호, 🎨 Design

#64 [Merge]#59-booth 페이지 QA 1차 해결
  src/components/BoothDetailBox/BoothDetailBox.jsx
  src/components/BoothDetailBox/BoothInfo.jsx
  src/components/BoothDetailBox/styled.js
  src/components/ClubInfo/RecruitInfo.jsx
  src/components/ExpandableText/ExpandableText.jsx
  src/components/Header/Header.jsx
  src/components/Header/styled.js
  src/components/Selector/styled.js
  src/hooks/Booth/useBoothInfo.js
  src/hooks/Booth/useFoodTruckInfo.js
  src/pages/Booth/BoothPage.jsx
  src/pages/Booth/FoodDetailPage.jsx
Labels: 🎨 Design, ☘️ 채민

#98 [Merge] 목요일, 만해광장 정보 초기 정렬
  index.html
  src/hooks/useBoothSelect.js
  src/pages/Booth/BoothPage.jsx
Labels: 🐞 Fix, ☘️ 세호

#99 [Deploy] 최종 배포
  index.html
  src/hooks/useBoothSelect.js
  src/pages/Booth/BoothPage.jsx
Labels: 🌏 Deploy, ☘️ 세호
